services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: hacatonTPU
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackaton_network

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hackaton_network

  web:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "backendApp.asgi:application"]
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - hackaton_network

networks:
  hackaton_network:

volumes:
  postgres_data:
  static_volume:
