# Generated by Django 4.2.16 on 2024-12-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deviceinspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinspection',
            name='device',
        ),
        migrations.DeleteModel(
            name='LightingMode',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='sensor',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceInspection',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
