# Generated by Django 4.2.16 on 2024-12-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_on', models.BooleanField(default=False)),
                ('fan_speed', models.IntegerField(blank=True, null=True)),
                ('door_open', models.BooleanField(default=False)),
                ('window_open', models.BooleanField(default=False)),
                ('led_brightness', models.IntegerField(blank=True, null=True)),
                ('auto_led_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('light_value', models.FloatField(blank=True, null=True)),
                ('color_value', models.FloatField(blank=True, null=True)),
                ('color_detected', models.BooleanField(default=False)),
                ('water_flow', models.FloatField(blank=True, null=True)),
                ('initial_volume', models.FloatField(blank=True, null=True)),
                ('storage_volume', models.FloatField(blank=True, null=True)),
                ('overflow', models.BooleanField(default=False)),
                ('voc_value', models.FloatField(blank=True, null=True)),
                ('voc_detected', models.BooleanField(default=False)),
                ('reed_switch_door', models.BooleanField(default=False)),
                ('reed_switch_window', models.BooleanField(default=False)),
                ('distance_value', models.FloatField(blank=True, null=True)),
                ('distance_detected', models.BooleanField(default=False)),
                ('current', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('gyro_x', models.FloatField(blank=True, null=True)),
                ('gyro_y', models.FloatField(blank=True, null=True)),
                ('gyro_z', models.FloatField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('fan_rpm', models.FloatField(blank=True, null=True)),
                ('earthquake_alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorSensor',
        ),
        migrations.DeleteModel(
            name='LightSensor',
        ),
        migrations.DeleteModel(
            name='MoistureSensor',
        ),
        migrations.DeleteModel(
            name='OverflowSensor',
        ),
        migrations.DeleteModel(
            name='WaterFlowSensor',
        ),
    ]
