# Generated by Django 4.2.16 on 2024-12-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_accelerometer_currentsensor_distancesensor_fan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('pump', 'Помпа'), ('led', 'Лента'), ('servo1', 'Серво №1'), ('servo2', 'Серво №2'), ('auto_light', 'Авто-свет'), ('brightness', 'Яркость'), ('authorization', 'Авторизация')], max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('user_name', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
