# Generated by Django 4.2.16 on 2024-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_command_user_name_command_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('earthquake', 'Земtags=["DeviceState"],летрясение'), ('ventilation', 'Режим проветривания')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('received_from', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
